### ISSUE TITLE
Implement a build system for modpack

### ISSUE THREAD

**Issue by xenia-foxtrot** [ILikePizza555/Ponydev-SFE-Modpack#10]
Okay, uploading `.mrfiles` is getting unwieldy. Especially since we need to manage both client and server mods, and installing client-side mods on the server breaks everything.

On top of that, we have mod configurations and datapacks we need to synchronize now.

I think this modpack needs some sort build system. I would use nix, but that doesn't work on Windows. Maybe i can write something simple in python?

**Comment by keupoz** [comment]
Try this
https://github.com/SKCraft/Launcher

**Comment by octylFractal** [comment]
Possibly use https://github.com/octylFractal/netherfire after a Modrinth rewrite.

**Comment by xenia-foxtrot** [comment]
With v1.3.3 this has been completed
